meta_product_name: "Planyourtrip"
meta_title: "Planyourtrip - OrganiseTesVacances"
meta_description: "Tu veux voyager en groupe ? Plus d'inquiétudes, viens planifier tout ça ici !"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
